name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      description: By submitting this issue, you agree to follow our Code of Conduct and confirm you've done the following
      options:
        - label: I have searched for existing issues that describe my problem
          required: true
        - label: I have read the contributing guidelines
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is and what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information
      placeholder: |
        - OS: [e.g. macOS 13.0, Windows 11, Ubuntu 22.04]
        - Browser: [e.g. Chrome 118, Firefox 119, Safari 17]
        - Version: [e.g. v1.2.3]
        - Node.js version: [if applicable]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop images here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. Include any workarounds you've found.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug for you?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but workaround exists
        - High - Blocks important functionality
        - Critical - Breaks core functionality or security issue
    validations:
      required: true